sudo: false
language: python
cache: pip
before_script:
- pip install -e '.[testing]'
script:
- flake8 *.py faereld
- black *.py faereld --check
- isort -c
- mypy faereld
notifications:
  email: false
matrix:
  include:
    - python: 3.6

